import type { Snapshot } from "./types";

export const mockSnapshot: Snapshot = {
  generatedAt: "",
  app: {
    name: "javis",
    ui: "web-shell",
    engine: "python",
  },
  project: {
    summary: "Codex-first 운영 어시스턴트를 web shell 중심 구조로 올리고 있습니다.",
    targetOutcome: "세련된 자비스 표면과 Python 운영 엔진 브리지를 점진적으로 완성합니다.",
    steps: [
      "Electron + React 셸을 세팅합니다.",
      "Python snapshot API를 연결합니다.",
      "Assistant Surface를 운영 표면으로 끌어올립니다.",
      "다음 단계에서 액션 브리지를 붙입니다.",
    ],
  },
  assistant: {
    badge: "SHELL",
    headline: "web shell 기반 자비스 전환을 진행 중입니다",
    summary: "아직 Python API 연결 전이라 데모 스냅샷을 보여주고 있습니다.",
    nextAction: "API를 띄우면 실제 프로젝트 상태로 자동 전환됩니다.",
  },
  surface: {
    stateKey: "demo_ready",
    projectLabel: "web shell migration",
    badgeLabel: "READY",
    title: "다음 단계 진행 준비가 되어 있습니다",
    summary: "지금은 데모 스냅샷 기준의 surface state를 보여주고 있습니다.",
    reason: "Python local API와 React shell이 아직 분리 실행 상태라 fallback snapshot을 사용 중입니다.",
    nextAction: "API를 켜고 실제 세션 상태를 연결해 주세요.",
    progressLabel: "진행 1/4",
    detailLabel: "점수 없음 | 안정 카운트 0 | 최근 캡처 없음",
    riskLabel: "낮음",
    actions: [
      { id: "continue", label: "진행", enabled: true, emphasis: "primary" },
      { id: "pause_auto", label: "보류", enabled: true, emphasis: "secondary" },
      { id: "voice_brief", label: "브리핑", enabled: true, emphasis: "secondary" },
      { id: "open_settings", label: "설정", enabled: true, emphasis: "secondary" },
    ],
  },
  runtime: {
    savedAt: "",
    progress: {
      current: 1,
      total: 4,
      ratio: 0.25,
    },
    currentStep: "Python snapshot API를 연결합니다.",
    lastCapturePath: null,
    lastTargetTitle: "Codex",
    lockStatus: "연결 대기",
    operatorPaused: false,
    operatorPauseReason: "",
    autoRunning: false,
  },
  codex: {
    strategyPresetId: "masterplan_followup",
    automationModeId: "recommended",
    deepIntegrationModeId: "recommended",
    liveOpsProfileId: "balanced",
  },
  queue: [
    {
      index: 0,
      total: 4,
      title: "Electron + React 셸을 세팅합니다.",
      status: "done",
      displayLine: "[완료] 1/4 Electron + React 셸을 세팅합니다.",
    },
    {
      index: 1,
      total: 4,
      title: "Python snapshot API를 연결합니다.",
      status: "current",
      displayLine: "[현재] 2/4 Python snapshot API를 연결합니다.",
    },
    {
      index: 2,
      total: 4,
      title: "Assistant Surface를 운영 표면으로 끌어올립니다.",
      status: "next",
      displayLine: "[다음] 3/4 Assistant Surface를 운영 표면으로 끌어올립니다.",
    },
  ],
  promptPreview: {
    hasStep: true,
    isComplete: false,
    stepIndex: 1,
    stepTitle: "Python snapshot API를 연결합니다.",
    source: "generated",
    excerpt: "현재 세션 상태를 JSON snapshot으로 노출하고, web shell이 이를 주기적으로 읽도록 구성합니다.",
    generatedPrompt: "",
    draftPrompt: "",
  },
  signals: [
    { label: "Codex Target", value: "Codex", tone: "good" },
    { label: "Lock Status", value: "연결 대기", tone: "muted" },
    { label: "Judgment", value: "pending", tone: "muted" },
    { label: "Loop Mode", value: "dry run", tone: "muted" },
  ],
  deckSections: [
    { id: "project", title: "Project", value: "web shell migration", description: "하이브리드 전환 세션", tone: "good" },
    { id: "strategy", title: "Codex Strategy", value: "masterplan_followup", description: "recommended", tone: "good" },
    { id: "judgment", title: "Judgment", value: "auto", description: "gpt-5.4-mini", tone: "good" },
    { id: "visual", title: "Visual", value: "auto", description: "targeted_only", tone: "muted" },
    { id: "voice", title: "Voice", value: "ko-KR", description: "brief on", tone: "good" },
    { id: "live-ops", title: "Live Ops", value: "balanced", description: "milestone", tone: "good" },
  ],
  recentProjects: [],
};
